services:
  web:
    build:
      context: .
      dockerfile: AIMS/Dockerfile
    ports:
      - "5119:5119"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - new-bridge-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "StrongP@ssword!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    networks:
      - new-bridge-net

networks:
  new-bridge-net:
    driver: bridge
